spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2console/
  jpa:
    show-sql: 'true'

security:
  jwt:
    secret-key: verysecretkeysosecrethatanybodyknowsthatkeysecret





